### ISSUE TITLE
RuntimeError Exception: can't modify frozen String

### ISSUE THREAD

**Issue by thorsteneckel** [robforman/tcr#23]
Hi @robforman - thanks for this great gem!

However, we encountered an issue with mocking an IMAP connection. TCR tries to force the UTF-8 encoding on frozen string which results in a `RuntimeError Exception: can't modify frozen String`.

Pull request is on the way 👍

**Comment by robforman** [comment]
very cool- thanks for the addition.

**Comment by thorsteneckel** [comment]
Thanks for your blazing fast response and the new release 💪 Works as expected. Closing now.
