### ISSUE TITLE
Doesn't work with net-ldap gem

### ISSUE THREAD

**Issue by rlue** [robforman/tcr#25]
When trying to record an LDAP connection with the [ruby-net-ldap](https://github.com/ruby-ldap/ruby-net-ldap) gem, TCR raises the following exception:

    Exceptions::UnprocessableEntity: Can't connect to 'localhost' on port '389', undefined method `read_ber' for #<TCR::RecordableTCPSocket:0x000055d461a080f8>

TCR is trying to mock out [the object returned by the `#socket` method in the fourth line below](https://github.com/ruby-ldap/ruby-net-ldap/blob/master/lib/net/ldap/connection.rb#L234) — but it looks like the method called on it is not implemented by the mock object:

```ruby
def read(syntax = Net::LDAP::AsnSyntax)
  ber_object =
    instrument "read.net_ldap_connection", :syntax => syntax do |payload|
      socket.read_ber(syntax) do |id, content_length|
        payload[:object_type_id] = id
        payload[:content_length] = content_length
      end
    end

  return unless ber_object

  instrument "parse_pdu.net_ldap_connection" do |payload|
    pdu = payload[:pdu]  = Net::LDAP::PDU.new(ber_object)

    payload[:message_id] = pdu.message_id
    payload[:app_tag]    = pdu.app_tag

    pdu
  end
end
```

Sorry I can't offer more clarity; I'm still not too familiar with what TCR is doing under the hood. Happy to help continue debugging this issue with your guidance, though!

**Comment by robforman** [comment]
Interesting. Is there a public LDAP service we can test against?

**Comment by robforman** [comment]
nvm- found it over in #26
