### ISSUE TITLE
Handling Shift-JIS Encoding

### ISSUE THREAD

**Issue by gillygize** [robforman/tcr#4]
I am working on a application which requires handling Shift-JIS as opposed to UTF-8 encodings.  I have found that saving the cassette to a file sometimes chokes (most likely due to the fact that the JSON library is expecting UTF-8).

By forking tcr and using yaml instead of json, I have been able to save the cassette data successfully.  Is this capability something of general interest?  Should I make a pull request?

**Comment by yukas** [comment]
Should close this issue as this the pull request https://github.com/robforman/tcr/pull/20 has already been merged?

**Comment by robforman** [comment]
Good call.
